sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
language: node_js
node_js: stable
os:
  - osx
branches:
  only:
    - master # build master branch only
install:
  - npm install
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: public/
  on:
    branch: master
    