sudo: false
language: node_js
node_js:
  - 8.11.0 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
install:
  - npm install
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  local-dir: public/
  on:
    branch: master
    