# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  Github: https://github.com/WorkPlusFE/blog
rss: /blog/atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics:
favicon: /blog/favicon.ico
